# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "I&mdash;S&mdash;O&mdash;P&mdash;T"
tagline:          "In search of Personalazed Time"
description:      "In search of Personalazed Time, Project by Taeyoon Choi and E Roon Kang. 2014–2015, Art + Technology Project, Los Angeles County Museum of Art (LACMA)"
url:              "http://isopt.github.io/"

author:
  name:           E Roon Kang
  url:            https://eroonkang.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/isopt
